services:
  db:
    container_name: nesttest_pg_container
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nesttestpass
      POSTGRES_DB: nesttestdb
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    ports:
      - '5679:5432'

  adminer:
    container_name: nesttest_adminer_container
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - '8980:8080'
